# Generated by Django 4.0.6 on 2024-06-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('descripcion', models.CharField(max_length=250, verbose_name='descripción')),
                ('precio_base', models.FloatField(default=0.0, verbose_name='precio_base')),
                ('iva', models.FloatField(default=1.0)),
                ('constante', models.FloatField(default=1.0)),
                ('ganancia', models.FloatField(default=1.0)),
                ('descuento_efectivo', models.FloatField(default=1.0)),
                ('descuento_cantidad', models.FloatField(default=1.0)),
                ('descuento_oferta', models.FloatField(default=1.0)),
                ('cantidad', models.FloatField(default=1.0)),
            ],
        ),
    ]
